### ISSUE TITLE
Question: Best bootstrap method for variance, standard deviation, and proportion

### ISSUE THREAD

**Issue by DrJerryTAO** [mayer79/cis#7]
Hi @mayer79, I wonder if bias-corrected and accelerated (BCA) bootstrapping performs better than student bootstrapping on confidence intervals of variance, standard deviation, and proportion. I loved your package for including student bootstrap confidence intervals, as it is rarely directly available in other packages. 

I noticed that the default bootstrap method for variance, standard deviation, and proportion is the BCA whereas that for mean is the student bootstrap. However, the student bootstrap method is available for all these statistics because their standard error formulae are known as what you included. From Hesterberg, T. C. (2015). What teachers should know about the bootstrap: Resampling in the undergraduate statistics curriculum. The American Statistician, 69(4), 371–386. https://doi.org/10.1080/00031305.2015.1089789, I understand that student bootstrap confidence intervals performs best for confidence intervals of means, as illustrated in Figure 10 by bootT. But is there any comparison between bootstrap method performance on confidence intervals of variance, standard deviation, and proportion?

**Comment by mayer79** [comment]
Hello and thanks for the good question. 

- I do not know any reference that would compare BCA and the Student approach for the variance/sd. If you find one, I'd be very interested.
- For proportions, there is no reason to use the Bootstrap. I'd rather go for some exact (conservative) method or Wilson's very strong apprximation.
- Should we consider changing the default to BCA for any except maybe the mean (and the mean difference)? It is fully generic, range-preserving and transformation respecting.

**Comment by DrJerryTAO** [comment]
> I do not know any reference that would compare BCA and the Student approach for the variance/sd. If you find one, I'd be very interested.

Me neither. I even wonder how student bootstrap CI for variance compares with parametric ones, as the latter is usually generated from a chi-square distribution without a standard error estimate. See DescTools:::VarTest.default(). 

> For proportions, there is no reason to use the Bootstrap. I'd rather go for some exact (conservative) method or Wilson's very strong approximation.

Why is bootstrap CI for proportions not a good idea? I can only think of extreme cases where x is nearly 0 or n, so the proportions are close to 0 and 1, where bootstrap CI would likely collapse to just 0 or 1. I agree that the century-old Wilson CI is a great candidate, selected for illustration by Beaulieu-Prévost, D. (2006). Confidence intervals: From tests of statistical significance to confidence intervals, range hypotheses and substantial effects. Tutorials in Quantitative Methods for Psychology, 2(1), 11–19. https://doi.org/10.20982/tqmp.02.1.p011 and Cumming, G., & Fidler, F. (2009). Confidence intervals: Better answers to better questions. Zeitschrift Für Psychologie/Journal of Psychology, 217(1), 15–26. https://doi.org/10.1027/0044-3409.217.1.15 and found to have the best actual coverage probability among several alternatives according to Oranje, A. (2006). Confidence intervals for proportion estimates in complex samples. ETS Research Report Series, 2006(2), i–26. https://doi.org/10.1002/j.2333-8504.2006.tb02027.x

> Should we consider changing the default to BCA for any except maybe the mean (and the mean difference)? It is fully generic, range-preserving and transformation respecting.

BCA should have a clear time advantage when the standard error formula is not available, so student bootstrapping cannot be easily implemented without a second round of resampling to estimate the standard error. However, I wonder if BCA and student bootstrap CIs of statistics other than means differ in actual coverage probability if computing time is not a concern.
