### ISSUE TITLE
Suggestion: Confidence intervals of ratio and difference in variance and standard deviation

### ISSUE THREAD

**Issue by DrJerryTAO** [mayer79/cis#8]
Hi @mayer79, would you consider adding function for confidence intervals of variance and standard deviation ratio and difference between two (independent) samples? I once wrote R functions that calculate student and percentile bootstrap confidence intervals of standard deviation ratios between two independent samples, based on both raw ratio and its logarithm. I do not think the asymptotic "normal" bootstrap is appropriate, as the ratios are usually skewed. It is probably better to generate confidence intervals of variance ratios first, then transform them to those of standard deviation ratios. I assume the logarithm of a ratio is less skewed than its raw form and possibly has a better property when forming confidence intervals, but I have not explored its theoretic or empirical basis. I can show my script if needed. 

The following sources might be helpful

- Asymptotic distribution of sample variance of non-normal sample relative to the population mu and sigma.  https://stats.stackexchange.com/questions/105337. 
- UW Matlab Example 3: Bootstrapping on a ratio of variances https://courses.washington.edu/matlab1/Bootstrap_examples.html#13
- Standard error of a ratio https://stats.stackexchange.com/questions/21167
- Variance of the reciprocal II https://stats.stackexchange.com/questions/19576
- Testing the significance of differences between ratios with small samples https://stats.stackexchange.com/questions/12069
- Kim, J. H. (2006). Wild bootstrapping variance ratio tests. Economics Letters, 92(1), 38–43. https://doi.org/10.1016/j.econlet.2006.01.007
- SE of variance and SD: https://stats.stackexchange.com/questions/156518

**Comment by mayer79** [comment]
Thanks a lot for this great input. I'd love to have some of those methods in {confintr}! Is your code publicly available?

Before adding new methods to {confintr}, I would like to improve the unit tests. Somehow, I find it very difficult to write good tests, especially with the Bootstrap.

**Comment by DrJerryTAO** [comment]
What did you mean by "unit tests?" 

You can find my script at https://github.com/MrJerryTAO/ under the file [balance.IPW_MrJerryTAO.R](https://github.com/MrJerryTAO/MrJerryTAO/blob/main/balance.IPW_MrJerryTAO.R). But I realized that I made a mistake in the variance of of the sample standard deviation. However, it might be better to use the variance of of the sample variance directly, as the formula for variance of of the sample standard deviation comes from a delta method approximation based on the variance of of the sample variance directly.

**Comment by mayer79** [comment]
Closed as too much is unclear to me.
