### ISSUE TITLE
Suggestion: student bootstrapped CIs for skewness and kurtosis

### ISSUE THREAD

**Issue by DrJerryTAO** [mayer79/cis#9]
Hi @mayer79, I noticed that the student bootstrapped CIs for skewness and kurtosis are provided in DescTools as their standard error formulae are given in the script of DescTools::Skew() and DescTools::Kurt(). You could consider incorporating this bootstrap option. Also note that DescTools has three methods of calculating skewness and kurtosis each, with the default method = 3 different from the typical definition as in method = 1. I have not investigated how the three methods compare with each other.

**Comment by mayer79** [comment]
Aa far as I remember, these standard errors are valid only under normality. Thus, I propose to stay with BCA.
